#pragma once

#include "utils.hpp"

#include <string.h>

#include <sdbusplus/asio/object_server.hpp>
#include <sdbusplus/bus/match.hpp>
#include <xyz/openbmc_project/SessionManager/KvmSessionInfo/server.hpp>

#include <algorithm>
#include <iostream>
#include <list>
#include <map>
#include <tuple>
#include <vector>

using IfcKvm =
    sdbusplus::server::xyz::openbmc_project::session_manager::KvmSessionInfo;

using kvmInfo =
    std::tuple<SessionId, IpAdress, UserName, SessionType, Previlage, UserId>;

constexpr auto kvmService = "start-ipkvm.service";
constexpr auto kvmsessionMgrObj = "/xyz/openbmc_project/SessionManager/kvm";

class KvmSessionManager : public IfcKvm
{
  public:
    KvmSessionManager(sdbusplus::bus_t& bus, const char* path) :
        IfcKvm(bus, path),
        crashMonitorSignal(
            bus, matchString,
            std::bind(std::mem_fn(&KvmSessionManager::crashMonitor), this,
                      std::placeholders::_1))

    {
        uid = 0;
    }

    /** @brief Implementation for KvmSessionRegister
     *  This dbus method adds KVM session information.
     *
     *  @param[in] sessionId - It’s a unique ID which will be generated by
     * session management. server must set it to 0 as default value.
     *  @param[in] ipAdress - IP Address of the remote machine from where BMC is
     * accessed
     *  @param[in] userName - Name of the user who is trying to access.
     *  @param[in] sessionType - session type
     *  @param[in] previlage - User Privilege
     *  @param[in] userId - userId
     *
     *  @return rsp[bool] - success or failure
     */

    bool kvmSessionRegister(uint8_t sessionId, std::string ipAdress,
                            std::string userName, uint8_t sessionType,
                            uint8_t previlage, uint8_t userId) override;

    /** @brief Implementation for KvmSessionUnregister
     *  This is the dbus method to unregister/delete session information.
     *
     *  @param[in] sessionId - session Id which to unregister.
     *  @param[in] sessionType - Type of Session(KVM = 0).
     *  @param[in] reason - reason for unregister/delete.
     *
     *  @return rsp[bool] - success or failure
     */

    bool kvmSessionUnregister(uint8_t sessionId, uint8_t sessionType,
                              uint8_t reason) override;
    /** @brief Implementation for ClearAll
     *  This dbus method delete all logged-in KVM session.
     *
     *  @return rsp[bool] - success or failure
     */

    bool clearAll() override;

  private:
    uint8_t uid;

    /** @brief React to JobRemoved signal
     *  @param[in] msg - sdbusplus message
     */
    void crashMonitor(sdbusplus::message_t& msg);
    sdbusplus::bus::match_t crashMonitorSignal;
};
