#pragma once

#include "utils.hpp"

#include <string.h>

#include <sdbusplus/asio/object_server.hpp>
#include <sdbusplus/bus/match.hpp>
#include <xyz/openbmc_project/SessionManager/VmediaSessionInfo/server.hpp>

#include <algorithm>
#include <iostream>
#include <list>
#include <map>
#include <tuple>
#include <vector>

using IfcVmedia =
    sdbusplus::server::xyz::openbmc_project::session_manager::VmediaSessionInfo;

using vmediaInfo = std::tuple<SessionId, IpAdress, UserName, SessionType,
                              Previlage, UserId, MountType, SlotId>;

constexpr auto vmediaService = "xyz.openbmc_project.VirtualMedia.service";
constexpr auto vmediasessionMgrObj =
    "/xyz/openbmc_project/SessionManager/vmedia";

class VmediaSessionManager : public IfcVmedia
{
  public:
    VmediaSessionManager(sdbusplus::bus_t& bus, const char* path) :
        IfcVmedia(bus, path),
        crashMonitorSignal(
            bus, matchString,
            std::bind(std::mem_fn(&VmediaSessionManager::crashMonitor), this,
                      std::placeholders::_1))
    {
        uid = 0;
    }

    /** @brief Implementation for VmediaSessionRegister
     *  This dbus method adds VMEDIA session information.
     *
     *  @param[in] sessionId - It’s a unique ID which will be generated by
     * session management. server must set it to 0 as default value.
     *  @param[in] ipAdress - IP Address of the remote machine from where BMC is
     * accessed
     *  @param[in] userName - Name of the user who is trying to access.
     *  @param[in] sessionType - session type
     *  @param[in] previlage - User Privilege
     *  @param[in] userId - userId
     *  @param[in] mountType - vmedia mounting method(console/remote)
     *  @param[in] slotId - vmedia slot ID
     *
     *  @return rsp[bool] - success or failure
     */
    bool vmediaSessionUnregister(uint8_t sessionId, uint8_t sessionType,
                                 uint8_t reason) override;

    /** @brief Implementation for VmediaSessionUnregister
     *  This is the dbus method to unregister/delete session information.
     *
     *  @param[in] sessionId - session Id which to unregister.
     *  @param[in] sessionType - Type of Session(VMEDIA = 2).
     *  @param[in] reason - reason for unregister/delete.
     *
     *  @return rsp[bool] - success or failure
     */

    bool vmediaSessionRegister(
        uint8_t sessionId, std::string ipAdress, std::string userName,
        uint8_t sessionType, uint8_t previlage, uint8_t userId,
        std::string mountType, std::string slotId) override;

  private:
    uint8_t uid;

    /** @brief React to JobRemoved signal
     *  @param[in] msg - sdbusplus message
     */
    void crashMonitor(sdbusplus::message_t& msg);
    sdbusplus::bus::match_t crashMonitorSignal;
};
