#pragma once

#include "utils.hpp"

#include <string.h>

#include <sdbusplus/asio/object_server.hpp>
#include <sdbusplus/bus/match.hpp>
#include <xyz/openbmc_project/SessionManager/WebSessionInfo/server.hpp>

#include <algorithm>
#include <iostream>
#include <list>
#include <map>
#include <tuple>
#include <vector>

using IfcWeb =
    sdbusplus::server::xyz::openbmc_project::session_manager::WebSessionInfo;

using webInfo =
    std::tuple<SessionId, IpAdress, UserName, SessionType, Previlage, UserId>;

constexpr auto webService = "bmcweb.service";
constexpr auto websessionMgrObj = "/xyz/openbmc_project/SessionManager/web";

class WebSessionManager : public IfcWeb
{
  public:
    WebSessionManager(sdbusplus::bus_t& bus, const char* path) :
        IfcWeb(bus, path),
        crashMonitorSignal(
            bus, matchString,
            std::bind(std::mem_fn(&WebSessionManager::crashMonitor), this,
                      std::placeholders::_1))
    {
        uid = 0;
    }

    /** @brief Implementation for WebSessionRegister
     *  This dbus method adds WEB session information.
     *
     *  @param[in] sessionId - It’s a unique ID which will be generated by
     * session management. server must set it to 0 as default value.
     *  @param[in] ipAdress - IP Address of the remote machine from where BMC is
     * accessed
     *  @param[in] userName - Name of the user who is trying to access.
     *  @param[in] sessionType - session type
     *  @param[in] previlage - User Privilege
     *  @param[in] userId - userId
     *
     *  @return rsp[bool] - success or failure
     */

    bool webSessionRegister(uint8_t sessionId, std::string ipAdress,
                            std::string userName, uint8_t sessionType,
                            uint8_t previlage, uint8_t userId) override;

    /** @brief Implementation for WebSessionUnregister
     *  This is the dbus method to unregister/delete session information.
     *
     *  @param[in] sessionId - session Id which to unregister.
     *  @param[in] sessionType - Type of Session(WEB = 1).
     *  @param[in] reason - reason for unregister/delete.
     *
     *  @return rsp[bool] - success or failure
     */

    bool webSessionUnregister(uint8_t sessionId, uint8_t sessionType,
                              uint8_t reason) override;

  private:
    uint8_t uid;

    /** @brief React to JobRemoved signal
     *  @param[in] msg - sdbusplus message
     */
    void crashMonitor(sdbusplus::message_t& msg);
    sdbusplus::bus::match_t crashMonitorSignal;
};
